### ISSUE TITLE
Cannot find tinyxml2 via pkg-config/cmake on win-64

### ISSUE THREAD

**Issue by anjos** [conda-forge/tinyxml2-feedstock#11]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I'm trying to have a win-64 build for another feedstock (libmediainfo) that uses this one.  This works well for linux-64 and osx-64, but not on win-64, with the same cmake configuration and build scripts.  Under win-64, the build system fails to find tinyxml2 for some reason I don't understand (very likely lack of experience).  I wonder if there is anything special I should either set on libmediainfo (in case the win-64 packaging of this feedstock is somewhat atypical?) to get this fixed?  The related PR is here: https://github.com/conda-forge/libmediainfo-feedstock/pull/7

To boil down, we are simply trying this:

```cmake
pkg_check_modules(PC_TINYXML QUIET tinyxml2)
```

**Comment by anjos** [comment]
Non issue, problem happened because of a side-effect of cmake-min-version < 3.1 at the downstream package.

**Comment by wolfv** [comment]
Great!
